### ISSUE TITLE
Converting from Qiime2

### ISSUE THREAD

**Issue by akknight** [ravel-lab/VALENCIA#1]
Hi- I'm interested in using this tool, but my output data is from Qiime2 so there are several ASVs that would fall into each of the species/genus categories in the reference. Do you have any suggestions as to how the data could be reformatted into what gets input into the package?

**Comment by michaelfrance** [comment]
Hi,
The general approach would be to sum read counts to ASVs belonging to the same taxon (e.g. all _L. crispatus_ ASVs get summed). If you can provide me with an example of your file format I would be happy to write a script to achieve this.

**Comment by michaelfrance** [comment]
Hi,
I have added a script which converts the output from Qiime2 to input for VALENCIA. Expected inputs are the ASV taxon name key file and the ASV counts table.
