### ISSUE TITLE
matching taxonomic names to VALENCIA reference set

### ISSUE THREAD

**Issue by kviljoen** [ravel-lab/VALENCIA#2]
Hi there,

Thanks for making this code available. I see there's an entry 'Prevotellaceae_bacterium' in the reference dataset – should this be added to f_Prevotellaceae?

Regards,
Katie.

**Comment by michaelfrance** [comment]
Hi Katie,

There is a slight difference between the "Prevotellaceae_bacterium'" and "f_Prevotellaceae" entries. In the case of "Prevotellaceae_bacterium", the sequence matches a specific 16S sequence which originates from a genome/isolate that had not yet been assigned taxonomy beyond being in the family Prevotellaceae. In the "f_Prevotellaceae" case, these sequences were unable to be assigned to a specific 16S sequence but were classified as generally belonging in Prevotellaceae.

**Comment by kviljoen** [comment]
Hi Michael,

Thanks for clarifying!
