### ISSUE TITLE
license needed

### ISSUE THREAD

**Issue by luhugerth** [ravel-lab/VALENCIA#9]
Hi,

VALENCIA doesn't currently have any license, which in principle means no-one can do anything with it: not clone, not copy, not modify, not distribute etc. In practice, anyone citing VALENCIA in a paper is admitting to a crime. Please add a simple license, such as the MIT model, as soon as possible. This protects the users, but also allows the research community to keep VALENCIA alive by e.g. packaging it for Qiime or Conda.

**Comment by michaelfrance** [comment]
Thanks for catching this, I have added a license.
